---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: server-side-ui-starter
spec:
 serviceAccountName: workload-installer
 packageRef:
   refName: server-side-ui-starter.workloads.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: server-side-ui-starter-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: server-side-ui-starter-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: server-side-ui-starter
