apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tanzu-java-web-app.workloads.tap.20240401233917.0.0+build.dea2ee9
spec:
  refName: tanzu-java-web-app.workloads.tap
  version: 20240401233917.0.0+build.dea2ee9
  releaseNotes: |
    Release v20240401233917.0.0+build.dea2ee9 of package tanzu-java-web-app.workloads.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: reg.perfect300rock.com/tapdev/supply-chain/tanzu-java-web-app-workloads-bundle@sha256:3603c4299c2718af416f370dea15b1470feceaf411cf9328d9fd2a87ebb1d69f
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

