---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: spring-streaming-processor
spec:
 serviceAccountName: workload-installer
 packageRef:
   refName: spring-streaming-processor.workloads.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: spring-streaming-processor-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: spring-streaming-processor-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   workload_name: spring-streaming-processor
