---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: csharp-weatherforecast
spec:
 serviceAccountName: workload-installer
 packageRef:
   refName: csharp-weatherforecast.workloads.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: csharp-weatherforecast-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: csharp-weatherforecast-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: csharp-weatherforecast
