---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: customer-profile
spec:
 serviceAccountName: workload-installer
 packageRef:
   refName: customer-profile.workloads.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: customer-profile-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: customer-profile-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: customer-profile
