---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: angular-frontend
spec:
 serviceAccountName: server-workload-installer  
 packageRef:
   refName: angular-frontend.workloads.tap # name of the Package
   versionSelection:
     constraints: '>=0.0.0'
 values:
 - secretRef:
     name: angular-frontend-package-values # Secret created in previous step
---
apiVersion: v1
kind: Secret
metadata:
 name: angular-frontend-package-values
stringData:
 values.yaml: |
   ---
   replicas: 1
   hostname: ""
   workload_name: angular-frontend
